=== Rodrigerzur/2021_LMGSI_RGZ/ExamenXML/mapaestelar.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT mapaestelar (constelacion|estrella)*>
<!ATTLIST mapaestelar
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>
<!ELEMENT constelacion (nombre|superficie|estrellas|objetos|colindantes|observacion)*>
<!ATTLIST constelacion nombreLatin CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterimsmo|masBrillante)*>
<!ATTLIST estrellas numero CDATA #IMPLIED>
<!ELEMENT asterimsmo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante luminosidad CDATA #IMPLIED>
<!ELEMENT objetos (cumulos|nebulosas|galaxias|cuasares|lluviademeteoros)*>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviademeteoros (nombre)*>
<!ELEMENT colindantes (nombre)*>
<!ELEMENT observacion (hemisferio|mes|hora)*>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT estrella (nombre|constelacionpertenece|distancia|luminosidad|temperatura|masa)*>
<!ELEMENT constelacionpertenece (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia medida CDATA #IMPLIED>
<!ELEMENT luminosidad (#PCDATA)>
<!ATTLIST luminosidad medida CDATA #IMPLIED>
<!ELEMENT temperatura (#PCDATA)>
<!ATTLIST temperatura medida CDATA #IMPLIED>
<!ELEMENT masa (#PCDATA)>
<!ATTLIST masa medida CDATA #IMPLIED>

=== Rodrigerzur/2021_LMGSI_RGZ/ExamenXML/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapaestelar SYSTEM 'mapaestelar.dtd'>
<mapaestelar
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
    <constelacion nombreLatin="Ursa Maior">
        <nombre>
            La Osa Mayor
        </nombre>
        <superficie>
            1297.7
        </superficie>
        <estrellas numero="209">
            <asterimsmo>
                7
            </asterimsmo>
            <masBrillante luminosidad="108">
                Alioth
            </masBrillante>
        </estrellas>
        <objetos>
            <cumulos>
                false
            </cumulos>
            <nebulosas>
                true
            </nebulosas>
            <galaxias>
                true
            </galaxias>
            <cuasares>
                false
            </cuasares>
            <lluviademeteoros>
                <nombre>
                    Kappa Ursa Mayoridas
                </nombre>
                <nombre>
                    Lambda Ursa Mayoridas
                </nombre>
                <nombre>
                    Psi Ursa Mayoridas
                </nombre>
                <nombre>
                    Ursa Mayoridas de octubre
                </nombre>
            </lluviademeteoros>
        </objetos>
        <colindantes>
            <nombre>
                Bootes
            </nombre>
            <nombre>
                Camelopardalis
            </nombre>
            <nombre>
                Canes Venatici
            </nombre>
            <nombre>
                Draco
            </nombre>
            <nombre>
                Leo
            </nombre>
            <nombre>
                Leo Minor
            </nombre>
            <nombre>
                Lynx
            </nombre>
        </colindantes>
        <observacion>
            <hemisferio>
                norte
            </hemisferio>
            <mes>
                04
            </mes>
            <hora>
                21:00:00
            </hora>
        </observacion>
    </constelacion>
    <estrella>
        <nombre>
            Alioth
        </nombre>
        <constelacionpertenece>
            Osa Mayor
        </constelacionpertenece>
        <distancia medida="aÃ±os luz">
            81
        </distancia>
        <luminosidad medida="soles"> 
            108  
        </luminosidad>
        <temperatura medida="K">
            9400
        </temperatura>
        <masa medida="soles">
            3
        </masa>
    </estrella>
</mapaestelar>
