=== Rodrigerzur/2021_LMGSI_RGZ/ud04/01.dtd
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT MIME (#PCDATA)>
<!ELEMENT fecha (dia,mes,anyo)>
<!ELEMENT ficheros (nombre, MIME)>
<!ELEMENT mail (remitente,destinatario+,asunto?,mensaje?,fecha,ficheros)>

=== Rodrigerzur/2021_LMGSI_RGZ/ud04/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail SYSTEM '01.dtd'>
<mail>
    <remitente>Rodrigo</remitente>
    <destinatario>Amor</destinatario>
    <destinatario>Meli </destinatario>
    <asunto>Practicas </asunto>
    <mensaje>Mis ejercicios </mensaje>
    <fecha> 
        <dia>28 </dia>
        <mes>01 </mes>
        <anyo>2021 </anyo>
    </fecha>
    <ficheros> 
        <nombre>ud04 </nombre>
        <MIME>.zip </MIME>
    </ficheros>
</mail>
