=== Rodrigerzur/2021_LMGSI_RGZ/ud04/12.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT receta (nombre,descripcion?,tiempo,ingredientes,instrucciones)>
<!ATTLIST receta
    plato (primero|segundo|postre) #REQUIRED >
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tiempo EMPTY>
<!ATTLIST tiempo
    preparacion CDATA #REQUIRED
    coccion CDATA #IMPLIED >
<!ELEMENT ingredientes (nombre,cantidad?)+>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad 
    unidad (gramos|pizca|mililitros|chorro|cucharada) #IMPLIED>
<!ELEMENT instrucciones (paso)+>
<!ELEMENT paso (#PCDATA)>

=== Rodrigerzur/2021_LMGSI_RGZ/12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta SYSTEM "12.dtd">
<receta plato="primero">
    <nombre>
        Risotto Milanesa
    </nombre>
    <descripcion>
        
    </descripcion>
    <tiempo preparacion="20" coccion="20"/>
    <ingredientes> 
        <nombre>Arroz</nombre>
        <cantidad unidad="gramos">500</cantidad>
    </ingredientes>
    <ingredientes> 
        <nombre>Cebolla mediana</nombre>
        <cantidad>1</cantidad>
    </ingredientes>
    <ingredientes> 
        <nombre>Azafran</nombre>
        <cantidad unidad="pizca">1</cantidad>
    </ingredientes>
    <ingredientes> 
        <nombre>queso parmesano</nombre>
        <cantidad unidad="gramos">100</cantidad>
    </ingredientes>
    <ingredientes> 
        <nombre>mantequilla</nombre>
        <cantidad unidad="gramos">100</cantidad>
    </ingredientes>
    <ingredientes> 
        <nombre>sal</nombre>
    </ingredientes>
    <ingredientes> 
        <nombre>pimienta</nombre>
    </ingredientes>
    <ingredientes> 
        <nombre>caldo</nombre>
        <cantidad unidad="mililitros">1000</cantidad>
    </ingredientes>
    <ingredientes> 
        <nombre>Vino Blanco</nombre>
        <cantidad unidad="chorro">1</cantidad>
    </ingredientes>
    <instrucciones>
        <paso>
            Picamos la cebolla y la pochamos con la mitad
de la mantequilla
        </paso>
        <paso>
            Cuando esté transparente, echamos el azafrán,
el vino y dejamos que reduzca
        </paso>
        <paso>
            A continuación, incorporamos el arroz, lo
sofreímos un poco.
        </paso>
        <paso>
            Vamos añadiendo el caldo caliente poco a poco
mientras removemos.
        </paso>
         <paso>
           Salpimentamos.
        </paso>
        <paso>
          Cuando esté casi hecho, agregamos el resto de
la mantequilla y el queso.
        </paso>
        <paso>
          Servimos enseguida.
        </paso>
    </instrucciones>
</receta>
